# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getWins <- function(PO) {
    .Call(`_TTLStandings_getWins`, PO)
}

getWins2 <- function(PO) {
    .Call(`_TTLStandings_getWins2`, PO)
}

getSets <- function(PO) {
    .Call(`_TTLStandings_getSets`, PO)
}

getSets2 <- function(PO) {
    .Call(`_TTLStandings_getSets2`, PO)
}

getSetWins <- function(PO) {
    .Call(`_TTLStandings_getSetWins`, PO)
}

getSetWins2 <- function(PO) {
    .Call(`_TTLStandings_getSetWins2`, PO)
}

getOPScores <- function(Sets, Wins) {
    .Call(`_TTLStandings_getOPScores`, Sets, Wins)
}

getStandings <- function(PO) {
    .Call(`_TTLStandings_getStandings`, PO)
}

getStandings2 <- function(PO) {
    .Call(`_TTLStandings_getStandings2`, PO)
}

getAllStandings <- function(PO) {
    .Call(`_TTLStandings_getAllStandings`, PO)
}

formatTime <- function(time) {
    .Call(`_TTLStandings_formatTime`, time)
}

getAllCombs <- function(W, total, verbose = TRUE) {
    .Call(`_TTLStandings_getAllCombs`, W, total, verbose)
}

getAllCombs2 <- function(W, total, verbose = TRUE) {
    .Call(`_TTLStandings_getAllCombs2`, W, total, verbose)
}

rcpp_hello_world <- function() {
    .Call(`_TTLStandings_rcpp_hello_world`)
}

